### ISSUE TITLE
Please create new release (or provide helm dev installation instructions)

### ISSUE THREAD

**Issue by nielsvm** [toboshii/hajimari#142]
**Describe the bug**
I was trying to get Hajimari running via Helm to use the CRD support. However, turns out the CRD wasn't getting installed and after manually installing it, I wouldn't pick up any `Application` resources.

Turns out that [v0.3.1](https://github.com/toboshii/hajimari/releases/tag/v0.3.1) doesn't yet ship this functionality.

I'd really like to use Hajimari but do depend on the new CRD support.

**Expected behavior**
Is it possible to get a new release cut?

Or could you provide instructions how to run a development version?

Thank you!

**Comment by nogweii** [comment]
Indeed, I was also looking for a new release to use the added CRD added. There have been [50 commits](https://github.com/toboshii/hajimari/compare/v0.3.1...main) since then. Most of them are version updates.

**Comment by mhaddon** [comment]
it just works providing you install the lastest helm and use a latest image:

        image:
          tag: main-f77fe68

**Comment by nogweii** [comment]
While that will probably work, I'd feel much better about it if it was actually declared as a stable version.

**Comment by klauserber** [comment]
Comming back to this after 2 years. This does not work anymore with the latest image (rke2 k8s 1.33.1):

```
time="2025-06-29T09:48:54Z" level=info msg="Using config file: /config/config.yaml" _source="hajimari/main.go:31"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa7420e]

goroutine 1 [running]:
github.com/toboshii/hajimari/internal/kube/lists/crdapps.(*List).Populate(0xc00045d498, {0xc0003f9240?, 0x4, 0xc000398a80?})
        /build/internal/kube/lists/crdapps/crdapps.go:46 +0x16e
github.com/toboshii/hajimari/internal/hajimari/crdapps.(*List).Populate(0xc00045da28, {0xc0003f9240?, 0xc000195720?, 0x182390c?})
        /build/internal/hajimari/crdapps/apps.go:39 +0xf8
github.com/toboshii/hajimari/internal/services.getKubeApps()
        /build/internal/services/app.go:89 +0x4d2
github.com/toboshii/hajimari/internal/services.NewAppService(0xc0003ecb00)
        /build/internal/services/app.go:39 +0x59
github.com/toboshii/hajimari/internal/handlers.NewHandler()
        /build/internal/handlers/handler.go:51 +0xa39
main.main()
        /build/cmd/hajimari/main.go:50 +0x1d
```
